import Head from "next/head";

export default function Login() {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="login-formmi w-screen h-screen">
                <div className="login-formmi-container">
                        <div className="login-formmi-title">
                            Masuk ke Formmi
                        </div>
                        <div className="login-formmi-form">
                            <form>
                                <div className="mb-2">
                                    <label htmlFor="email" className="form-label">Username atau Email</label>
                                    <input type="email" className="form-login" id="email" />
                                </div>
                                <div className="mb-3">
                                    <div className="d-flex justify-content-between">
                                        <label htmlFor="password" className="form-label">Password</label>
                                        <a href="/"><span className="lupa-password">Lupa password?</span></a>
                                    </div>
                                    <input type="password" className="form-login" id="password" />
                                </div>
                                
                                <button type="submit" className="btn btn-success btn-login">
                                    Masuk
                                </button>
                            </form>
                        </div>
                        <div className="buat-akun">
                            Baru di Formmi? <a href="/auth/registrasi"><span className="link-ancor">Buat akun sekarang</span></a>
                        </div>
                        <div className="tambahan-aja"></div>
                </div>
            </main>
        </>
    )
}